[package]
name = "flicky"
edition = "2024"
license = "Apache-2.0"
authors = ["Flicky Labs <lequocuyit@gmail.com>"]

[dependencies]
deepbook_predict = { local = "./deepbook_predict_min" }
deepbook = { local = "./deepbook_min" }
token = { local = "./token_min" }

[addresses]
flicky = "0x0"

[dev-dependencies]

[dev-addresses]
