/**
 * First-time publish of the flicky Move package to Sui testnet.
 *
 *   bun run publish
 *
 * Reads deployer keypair from .env.local (SUI_DEPLOYER_PRIVATE_KEY) or falls
 * back to a clear error if not set. Writes captured ids into `deployed.json`.
 *
 * After publish, run `bun run codegen` to regenerate TS bindings into
 * apps/web/src/sui/gen.
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { config as loadEnv } from "dotenv";

import { SuiJsonRpcClient, getJsonRpcFullnodeUrl } from "@mysten/sui/jsonRpc";
import { Transaction } from "@mysten/sui/transactions";
import { Ed25519Keypair } from "@mysten/sui/keypairs/ed25519";
import { decodeSuiPrivateKey } from "@mysten/sui/cryptography";

// -----------------------------------------------------------------------------

loadEnv({ path: resolve(import.meta.dir, "../.env") });
loadEnv({ path: resolve(import.meta.dir, "../.env.local"), override: true });

const NETWORK = (process.env.SUI_NETWORK ?? "testnet") as
  | "testnet"
  | "mainnet"
  | "devnet"
  | "localnet";

const DEPLOYED_JSON = resolve(import.meta.dir, "../deployed.json");
const PUBLISHED_TOML = resolve(import.meta.dir, "../Published.toml");

/**
 * Keep `Published.toml` in sync with the publish we just executed.
 * Sui Move's CLI writes this file on `sui move publish` but our
 * publish path uses the TS SDK + `sui move build`, so we have to
 * mirror the write ourselves. Without this, anyone reading
 * Published.toml as ground truth (other Move packages depending on
 * flicky, codegen tools, on-chain explorers) sees a stale address.
 */
function syncPublishedToml(packageId: string, upgradeCap: string, chainId: string): void {
  // Minimal but valid Published.toml — matches the shape the Sui CLI
  // emits. Preserve a `[published.<network>]` section per environment.
  const existing = existsSync(PUBLISHED_TOML)
    ? readFileSync(PUBLISHED_TOML, "utf-8")
    : ""
  const section = `[published.${NETWORK}]
chain-id = "${chainId}"
published-at = "${packageId}"
original-id = "${packageId}"
version = 1
toolchain-version = "1.64.0"
build-config = { flavor = "sui", edition = "2024" }
upgrade-capability = "${upgradeCap}"`

  let next: string
  const sectionHeader = `[published.${NETWORK}]`
  if (existing.includes(sectionHeader)) {
    // Replace just this network's block.
    next = existing.replace(
      new RegExp(`\\[published\\.${NETWORK}\\][\\s\\S]*?(?=\\n\\[|$)`),
      section,
    )
  } else {
    const banner =
      "# Generated by Move\n" +
      "# This file contains metadata about published versions of this package in different environments\n" +
      "# This file SHOULD be committed to source control\n\n"
    next = existing
      ? existing.trimEnd() + "\n\n" + section + "\n"
      : banner + section + "\n"
  }
  writeFileSync(PUBLISHED_TOML, next)
}

// -----------------------------------------------------------------------------

/**
 * `sui move build --dump-bytecode-as-base64` only emits the package's
 * *immediate* dependencies (as declared in Move.toml). Sui's on-chain
 * publish validation (`build_linkage_table` in sui-types) additionally
 * requires that every dependency's own linkage table be a subset of the
 * ids we pass — i.e. the FULL transitive closure, not just the direct
 * deps. This matters here because `deepbook_predict_min`'s `published-at`
 * points at the real, already-deployed DeepBook Predict package, which
 * itself has several further on-chain dependencies that our local
 * (trimmed) Move.toml no longer declares. Walking each dependency's
 * on-chain `linkage_table` (via `sui client object --json`) and unioning
 * it in reproduces what a fully-declared manifest would have produced.
 * Without this, publish fails with `PublishUpgradeMissingDependency`.
 */
function getOnChainLinkageDeps(pkgId: string): string[] {
  const out = execSync(`sui client object ${pkgId} --json`, {
    env: { ...process.env, PATH: `/opt/homebrew/bin:${process.env.PATH}` },
    maxBuffer: 200 * 1024 * 1024,
  }).toString();
  const obj = JSON.parse(out) as {
    content?: { Package?: { linkage_table?: Record<string, { upgraded_id: string }> } };
  };
  const linkageTable = obj.content?.Package?.linkage_table ?? {};
  return Object.values(linkageTable).map((v) => v.upgraded_id);
}

function computeTransitiveDependencyClosure(seedDependencies: string[]): string[] {
  const seen = new Set<string>(seedDependencies);
  const queue = [...seedDependencies];
  while (queue.length > 0) {
    const id = queue.pop()!;
    let deps: string[];
    try {
      deps = getOnChainLinkageDeps(id);
    } catch {
      // Not a package object we can introspect (or object doesn't exist) —
      // leave it to the on-chain validator to reject if it's actually bad.
      continue;
    }
    for (const dep of deps) {
      if (!seen.has(dep)) {
        seen.add(dep);
        queue.push(dep);
      }
    }
  }
  return [...seen];
}

async function main() {
  const keypair = loadDeployerKeypair();
  const address = keypair.toSuiAddress();
  const client = new SuiJsonRpcClient({
    url: process.env.SUI_RPC_URL ?? getJsonRpcFullnodeUrl(NETWORK),
    network: NETWORK,
  });

  console.log(`Deployer: ${address}`);
  console.log(`Network:  ${NETWORK}`);
  console.log(`Sui CLI:  ${execSync("sui --version", { env: { ...process.env, PATH: `/opt/homebrew/bin:${process.env.PATH}` } }).toString().trim()}`);

  // 1. Compile + emit bytecode via the Sui CLI.
  const buildOutput = JSON.parse(
    execSync("sui move build --dump-bytecode-as-base64 --path .", {
      cwd: resolve(import.meta.dir, ".."),
      env: { ...process.env, PATH: `/opt/homebrew/bin:${process.env.PATH}` },
    }).toString(),
  ) as { modules: string[]; dependencies: string[]; digest?: number[] };

  console.log(
    `Compiled ${buildOutput.modules.length} modules, ${buildOutput.dependencies.length} direct deps:`,
    JSON.stringify(buildOutput.dependencies, null, 2)
  );

  // 1b. Expand to the full transitive dependency closure — see
  //     computeTransitiveDependencyClosure() for why this is necessary.
  const dependencies = computeTransitiveDependencyClosure(buildOutput.dependencies);
  console.log(
    `Resolved ${dependencies.length} transitive deps:`,
    JSON.stringify(dependencies, null, 2)
  );

  // 2. Build the publish transaction.
  const tx = new Transaction();
  const upgradeCap = tx.publish({
    modules: buildOutput.modules,
    dependencies,
  });
  tx.transferObjects([upgradeCap], address);
  tx.setSender(address);

  // 3. Execute.
  let result;
  try {
    result = await client.signAndExecuteTransaction({
      transaction: tx,
      signer: keypair,
      options: { showEffects: true, showObjectChanges: true },
    });
  } catch (err: any) {
    console.error("FULL ERROR DETAILS:");
    console.error(JSON.stringify(err, null, 2));
    console.error(err);
    process.exit(1);
  }

  if (result.effects?.status?.status !== "success") {
    console.error("Publish failed:", result.effects?.status);
    process.exit(1);
  }

  // 4. Extract packageId + UpgradeCap. Flicky has no `init` functions, so
  //    no extra shared objects/caps come out of the publish tx.
  const changes = result.objectChanges ?? [];
  const packageChange = changes.find((c) => c.type === "published") as
    | { packageId: string }
    | undefined;
  if (!packageChange) {
    console.error("No package id in objectChanges — aborting.");
    process.exit(1);
  }
  const packageId = packageChange.packageId;
  const upgradeCapId = findObjectId(changes, "0x2::package::UpgradeCap");

  if (!upgradeCapId) {
    console.error("UpgradeCap not in objectChanges — aborting.");
    process.exit(1);
  }

  const deployed = {
    network: NETWORK,
    packageId,
    originalPackageId: packageId,
    publishedAt: new Date().toISOString(),
    publishTxDigest: result.digest,
    publisherAddress: address,
    upgradeCap: upgradeCapId,
    notes: "Written by scripts/publish.ts. originalPackageId is preserved across upgrades.",
  };

  writeFileSync(DEPLOYED_JSON, JSON.stringify(deployed, null, 2) + "\n");
  console.log(`\nWrote ${DEPLOYED_JSON}`);
  console.log(deployed);

  // Mirror to Published.toml so both files agree on the active address.
  try {
    const chainId = await client.getChainIdentifier();
    syncPublishedToml(packageId, upgradeCapId, chainId);
    console.log(`Wrote ${PUBLISHED_TOML} (chain-id=${chainId})`);
  } catch (e) {
    console.warn(
      `Failed to sync Published.toml: ${e instanceof Error ? e.message : String(e)}.\n` +
        `deployed.json is the source of truth; update the toml manually if needed.`,
    );
  }

  // Mirror packageId into apps/web/.env.local so Vite picks up the new id
  try {
    const envPath = resolve(import.meta.dir, "../../web/.env.local");
    const envKey = `VITE_FLICKY_PACKAGE_ID_${NETWORK.toUpperCase()}`;
    const wrote = upsertEnvVar(envPath, envKey, packageId);
    console.log(`Wrote env:               ${envPath} :: ${envKey} (${wrote})`);
  } catch (e) {
    console.warn(`Failed to write env.local: ${e instanceof Error ? e.message : String(e)}`);
  }
}

// -----------------------------------------------------------------------------

function loadDeployerKeypair(): Ed25519Keypair {
  const privKey = process.env.SUI_DEPLOYER_PRIVATE_KEY;
  if (!privKey) {
    console.error(
      "SUI_DEPLOYER_PRIVATE_KEY not set. Export your active key:\n" +
        "  sui keytool export --key-identity $(sui client active-address)\n" +
        "and paste it into apps/contracts/.env.local as SUI_DEPLOYER_PRIVATE_KEY.",
    );
    process.exit(1);
  }
  const { secretKey } = decodeSuiPrivateKey(privKey);
  return Ed25519Keypair.fromSecretKey(secretKey);
}

function findObjectId(changes: any[], objectType: string): string | null {
  const found = changes.find(
    (c) => c.type === "created" && c.objectType === objectType,
  ) as { objectId: string } | undefined;
  return found?.objectId ?? null;
}

function upsertEnvVar(envPath: string, key: string, value: string): string {
  if (!existsSync(envPath)) {
    writeFileSync(envPath, `${key}=${value}\n`);
    return "missing-file → created";
  }
  const original = readFileSync(envPath, "utf-8");
  const re = new RegExp(`^${key}=.*$`, "m");
  if (re.test(original)) {
    writeFileSync(envPath, original.replace(re, `${key}=${value}`));
    return "updated";
  }
  const suffix = original.endsWith("\n") ? "" : "\n";
  writeFileSync(envPath, `${original}${suffix}${key}=${value}\n`);
  return "appended";
}

// -----------------------------------------------------------------------------

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
